package br.com.whitewall.domain.enums;

public enum AuditAction {
    USER_LOGIN,
    USER_CREATED,
    USER_UPDATED,
    USER_DEACTIVATED,

    TOOL_CREATED,
    TOOL_UPDATED,
    TOOL_DEACTIVATED,

    RULE_CREATED,
    RULE_UPDATED,
    RULE_DEACTIVATED,

    DOCUMENT_SUBMITTED,
    DOCUMENT_ALLOWED,
    DOCUMENT_BLOCKED,
    APPROVAL_REQUESTED,
    DOCUMENT_APPROVED,
    DOCUMENT_REJECTED
}